version: '3'

services:
  botpress_main:
    image: botpress/server:v12_26_5
    container_name: botpress_main
    command: /botpress/bp
    expose:
      - 3000
    environment:
      - DATABASE_URL=postgres://postgres:secretpw@postgres:5435/botpress_db
      - BP_MODULE_NLU_DUCKLINGURL=http://botpress_lang:8000
      - BP_MODULE_NLU_LANGUAGESOURCES=[{"endpoint":"http://botpress_lang:3100"}]
      - CLUSTER_ENABLED=false
      - BP_PRODUCTION=false
      - BPFS_STORAGE=database
    depends_on:
      - botpress_lang
      - postgres
    volumes:
      - ./botpress/data:/botpress/data
    ports:
      - "3000:3000"

  botpress_lang:
    image: botpress/server:v12_26_5
    container_name: botpress_lang
    command: bash -c "./duckling -p 8000 & ./bp lang --langDir /botpress/lang --port 3100"
    expose:
      - 3100
      - 8000
    ports:
      - "3100:3100"
      - "8000:8000"

  postgres:
    image: postgres:14.0-alpine
    container_name: botpress_postgres
    expose:
      - 5435
    environment:
      PGPORT: 5435
      POSTGRES_DB: botpress_db
      POSTGRES_PASSWORD: secretpw
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5435"

volumes:
  pgdata:

